### ISSUE TITLE
tests fail on R-devel

### ISSUE THREAD

**Issue by qgeissmann** [rethomics/behavr#38]
**Only in developmental version of R.**
We get the same error as https://github.com/Rdatatable/data.table/issues/2820. This breaks all the package in rethomics in dev, but this being worked on upstream, so likely won't affect us.

**Comment by qgeissmann** [comment]
e.g.

```
> dt <- toy_activity_data(metadata, duration = days(2))
> 
> # average by 30min time bins, default
> dt_binned <- bin_apply_all(dt, moving)
Error in `[.data.table`(data, , bin_apply(data = .SD, ...), by = eval(data.table::key(data))) : 
  SETLENGTH() cannot be applied to an ALTVEC object.
Calls: bin_apply_all -> [ -> [.behavr -> NextMethod -> [.data.table
Execution halted
```

**Comment by mattdowle** [comment]
v1.11.2 is on CRAN now.  The NEWS entry is : 

> Fixed SETLENGTH() cannot be applied to an ALTVEC object starting in R-devel (R 3.6.0) on 1 May 2018, a few hours after 1.11.0 was accepted on CRAN, #2820. Many thanks to Luke Tierney for pinpointing the problem.
