### ISSUE TITLE
bind behavr objects

### ISSUE THREAD

**Issue by estebanbeck** [rethomics/behavr#39]
My goal is to put together 2 behavr objects that have the same set of metadata columns. 

It there a straightforward option to do it? With data.table I can do:

```R
dt_new <- dt_A[dt_B]
```

But it is not working with behavr objects....

**Comment by qgeissmann** [comment]
By "put together", do you mean bind rows? or maybe join them?
any chance you could provide a small example and the expected result?
e.g. Could you adapt the example from `?bind_behavr_list`:

```R
met <- data.table::data.table(id = 1:5,
							  condition = letters[1:5],
							  sex = c("M", "M", "M", "F", "F"),
							  key = "id")
data <- met[,list(t = 1L:100L,
			   x = rnorm(100),
			   y = rnorm(100),
			   eating = runif(100) > .5),
			   by = "id"]
d1 <- behavr(data, met)

met[,id := id + 5]
data[,id := id + 5]
data.table::setkeyv(met, "id")
data.table::setkeyv(data, "id")

d2 <- behavr(data, met)
d_all <- bind_behavr_list(list(d1, d2))
print(d_all)
```

**Comment by estebanbeck** [comment]
That solves the issue! Thanks.
