### ISSUE TITLE
linking data that is not from dam or ethoscope

### ISSUE THREAD

**Issue by brooksminer** [rethomics/behavr#42]
Hi! I am an experienced R user and would love to use the Rethomics framework to analyze activity data collected from a videotracking system my colleague developed for me using python.

I've had some successes creating behavr tables with activity data generated by our system. However I'm having trouble with timestamps and ZT0.

If I were able to use link_dam_metadata(), I could easily pull out a subset of the raw data defined by start_datetime and stop_datetime. But my raw data is not in the DAM format. (I could force my raw data into the DAM format but that would be cumbersome and would require creating a bunch of empty columns to match the DAM monitor data format... lots of unnecessary data storage that way too.)

Really what I want to do is quite simple. My raw data has three columns:
id, datetime, activity

There is one row per individual per second. (E.g., datetime is "2020-08-04 15:40:01" followed by  "2020-08-04 15:40:02" in the next row.)

I want to link my metadata to my raw data in a way that uses the datetime column in the raw data as the location to apply start_datetime and stop_datetime, as I would if using link_dam_metadata().

Would be *SO* delighted if you all could help me out! I'm excited to use the Rethomics framework if I can get it to work for me.

**Comment by qgeissmann** [comment]
Hi @brooksminer, thanks for your interest!
That sounds great. SO I am curious whether we are talking of one file, or multiple files. In the first case, we can just bypass the linking and just use `behavr()`. Linking makes sense when one has multiple files, or some sort of formal database to essentially subset and decorate with metadata. If you have multiple filers, could you please describe how they are organised and named? 

If we just want to be able to subset one file with a pair of dates (start and end), we can follow the same strategy as :https://github.com/rethomics/damr/blob/master/R/read-dam-file.R: 
1. read all date in a file
2. find the rows that match a range
3. read the actual file
4. we use the start time as zt0, which means the user can implicitly define zt0 their metadata

**Comment by brooksminer** [comment]
Hi @qgeissman, thanks for your prompt reply! 
All of the data is in one file, so I guess linking is not necessary! That simplifies things.

To be honest, I don't really need to subset my data by start and stop times. It would be fine to always import my complete dataset.

The real issue is how to set ZT0. I have successfully created behavr tables of my data, but ZT0 is *always* the first entry in the dataset.

Is there a way I can set or change the ZT0 of my behavr table?

**Comment by qgeissmann** [comment]
@brooksminer 
yes, by convention, time is in seconds. And you can just express it as a reference to whatever time you want, for instance, you could store a reference time in the metadata, which could be the zt0 on the first day of your experiment. Here is an example -- let me know if it makes sense:

```R
library(fasttime)
library(behavr)


# data <- fread('mydata.csv')
# for exple:
data.table(id=1, datatime = '2019-01-10 10:00:00', activity=1)

# meta <- fread('mymetadata.csv')
# for exple:
meta <- data.table(id=1, ref_datetime = '2019-01-10 08:00:00', genotype='wt')

## IMPORTANT, timezone matters, either the input file has explicit timezone, or is in utc, or ...
data[,datatime := fastPOSIXct(datatime, tz='UTC')]
meta[,ref_datetime := fastPOSIXct(ref_datetime, tz='UTC')]

setkey(data, 'id')
setkey(meta, 'id')

dt <- behavr(data, meta)

# t in, seconds, is the difference between the datetime of the read (data), 
# and the reference datetime, which is a metavariable  (hence the use `xmv()`)
# i.e. `t` is how long since reference. in this example, (2019-01-10) 08:00:00 is ZT0

dt[, t:=as.numeric(datatime - xmv(ref_datetime),units='secs')]
print(dt)
```

**Comment by brooksminer** [comment]
Thanks so much! The code you sent was super helpful, and I have now created a straightforward script for converting my data output from python into a behavr table with ZT0 encoded correctly.

Thanks noting the importance of timezone. Out of curiosity, I tried running my script without specifying the tz as you suggested, and it the result was incorrect encoding of ZT0.

**Comment by qgeissmann** [comment]
no problem. closing the issue then. yes, the default is R is to use the system's local timezone... and unsure how you have your time located in your input file, but I would say UTC saves your day :smile:
