### ISSUE TITLE
rejoin returns emtpy data table

### ISSUE THREAD

**Issue by pepelisu** [rethomics/behavr#8]
After creating some data with `toy_*_data`, and summarizing it using `rejoin` gives back an empty `data.table`.

Steps to reproduce:
```r
query <- data.frame(experiment_id="toy_experiment",
                   region_id=1:32, # 40 animals
                   condition=c("A","B"), # conditions A,B,A,B ...
                   # drift is a coeficient to drift the time so that we make 
                   # to slightly different periods see below
                   drift=c(1.001,1.000)
 )
toy_data <- toy_activity_data(query, duration = days(10))
toy_data[, t := as.integer(t/60)] #new time in minutes
summary_toy_data <- toy_data[, .(counts=sum(moving)), by=.(id,t)]
summary_all<-rejoin(summary_toy_data)
```
`summary_all` is then a empty data.table.

**Comment by qgeissmann** [comment]
Thanks!
So the problem starts when doing `toy_data[, .(counts=sum(moving)),  by=.(id,t)]`. 
This changes the key: 

```r
data.table::key(summary_toy_data)
#> [1] "id" "t" 
```
The default behaviour of `behavr` (pun intended ;)) is to coherce the returned table to a `data.table`. 
Then rejoin fails.

So we should:

- [ ] make sure rejoin only input a `behavr` table see #4 
- [ ] make unittests to check that
- [ ] find a better way to do what you are trying to do

**Comment by qgeissmann** [comment]
A simple and efficient way to do it. We group by ID, then, within each group, we resample/aggregate:

```r
summary_toy_data <- toy_data[, 
                             .SD[, .(count=sum(moving)), by="t"], 
                             by="id"]
```
